tmc_new/apps/crm/urls.py
from django.urls import path

from apps.crm.views import ClientCallFormView, ClientCallListView, ReportFormView, ClientCallDetailView, \
    ComplaintListView, ComplaintUpdateView

app_name = 'crm'

urlpatterns = (
    path('calls/', ClientCallListView.as_view(), name='clientcall_list'),
    path('calls/<int:pk>/', ClientCallDetailView.as_view(), name='clientcall_detail'),
    path('call-form/', ClientCallFormView.as_view(), name='new_clientcall_form'),
    path('call-form/<slug:phone>/', ClientCallFormView.as_view(), name='clientcall_form'),
    path('reports/create/', ReportFormView.as_view(), name='report_form'),
    path('complaints/', ComplaintListView.as_view(), name='complaint_list'),
    path('complaints/<int:pk>/update/', ComplaintUpdateView.as_view(), name='complaint_update'),
)

tmc_new/apps/surveys/urls.py
from django.urls import path

from apps.surveys.views import SurveyView

app_name = 'surveys'

urlpatterns = [
    path('<int:pk>/', SurveyView.as_view(), name='survey'),
]

tmc_new/apps/users/urls.py
from django.urls import path, include

from apps.users.views import CabinetIndexView, CabinetUpdateUserInfo

app_name = 'users'

urlpatterns = [
    path('cabinet/',
         include(([
                      path('', CabinetIndexView.as_view(), name='index'),
                      path('update-info/', CabinetUpdateUserInfo.as_view(), name='update_user_info'),
                  ], 'cabinet'))),
]

tmc_new/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from django.views.static import serve
from django.contrib.staticfiles.urls import static
from .settings import MEDIA_URL, MEDIA_ROOT, STATIC_ROOT

from apps.common.views import IndexView
from apps.crm.views import ClientCallFormView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Main.as_view(), name='main'),
    # АВТОРИЗАЦИЯ
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # КОНЕЦ АВТОРИЗАЦИИ
    path('card/', Card.as_view(), name='card'),
    path('card/<int:id>', Card_id.as_view(), name='card_id'),
    # path('add_form/<int:id>', additional_form, name='form'),
    #MAIN
    path('count/', get_count, name='count'),
    path('card/<int:patient_id>/setcount', CountCalls, name='count-calls'),
    #ЧЕК ЛИСТЫ
    path('card/checklist/save/<int:id>', CheckListSaveView.as_view(), name='checklist-save'),
    path('card/checklists/journal/<int:id>', CheckListJournalView.as_view(), name='checklist-journal'),
    #path('card/checklists/calls/<int:id>', CheckListCallsView.as_view(), name='checklist-calls'),
    # path('card/checklists/patients/<int:id>', CheckListPatientsView.as_view(), name='checklist-patients'),

    #TEST
    path('card/test/', set_users, name='test'),
    path('card/test/get', parse_users, name='test-get'),
    path('card/checklists/<int:id>', CheckListJournalView.as_view(), name='checklists-journal'),

    #api
    path('api/spmsps/', get_s_pmsp.as_view()),
    path('api/sregions/', get_s_region.as_view()),
    path('api/sselos/', get_s_selo.as_view()),
    path('api/scountrys/', get_s_country.as_view()),
    path('api/get-patient/', get_patient.as_view()),
    path('api/get-patient-id/', get_patient_id.as_view()),
    path('api/get-incident/', get_incident.as_view()),
    path('api/get-subtypecall/', get_s_subtypecall.as_view()),
    path('api/get-typecall/', get_s_typecall.as_view()),
    path('api/get-appeal-status/', get_s_appeal_status.as_view()),
    path('api/save-appeal/', save_appeal.as_view()),
    path('api/get-history/', get_history.as_view()),
    path('api/get-history-for-user/', get_history_all_for_current_user.as_view()),
    path('api/get-history-all/', get_history_all.as_view()),
    path('api/get-call-detail/', ReportsView.as_view()),
    path('api/auth/', api_auth.as_view()),

    re_path(r'static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    # 
    path('index/', IndexView.as_view(), name='index_page'),
    path('crm/', include('apps.crm.urls')),
    path('surveys/', include('apps.surveys.urls')),
    # path('users/', include('apps.users.urls')),
    path('phone/<slug:phone>/', ClientCallFormView.as_view(), name='clientcall_form'),
]

urlpatterns += static(MEDIA_URL, document_root = MEDIA_ROOT)

tmc_new/apps/geo/forms.py
from django.forms import ModelForm

from apps.geo.models import Region


class RegionModelForm(ModelForm):
    class Meta:
        model = Region
        fields = ['name']

tmc_new/apps/organizations/forms.py
from django.forms import ModelForm

from apps.organizations.models import Organization


class OrganizationModelForm(ModelForm):
    class Meta:
        model = Organization
        fields = ['name', 'region']

tmc_new/apps/users/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import ModelForm

from apps.users.models import User


class UserModelForm(ModelForm):
    helper = FormHelper()
    helper.add_input(Submit('submit', 'сохранить', css_class='btn-block'))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'patronymic', 'last_name', 'email']

tmc_new/apps/common/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.views.generic import TemplateView

from apps.crm.models import ClientCall, Complaint


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['clientcall_count_all'] = ClientCall.objects.all().count()
        context['clientcall_count_month'] = ClientCall.objects.filter(
            created__month=timezone.now().month).count()
        context['complaint_count_all'] = Complaint.objects.count()
        context['complaint_count_month'] = Complaint.objects.filter(
            created__month=timezone.now().month).count()
        return context

tmc_new/apps/crm/views.py
import xlwt
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import CreateView, ListView, FormView, DetailView, UpdateView

from apps.common.xls_styles import BOLD_CELL_CENTER
from apps.crm.forms import ClientCallModelForm, ComplaintModelForm, ClientModelForm, ReportForm, \
    ConsultationModelForm, ComplaintUpdateModelForm
from apps.crm.models import ClientCall, Complaint
from apps.handbook.models import Category


class ClientCallDetailView(LoginRequiredMixin, DetailView):
    model = ClientCall
    template_name = 'crm/clientcall_detail.html'


# noinspection PyAttributeOutsideInit
class ClientCallFormView(LoginRequiredMixin, CreateView):
    template_name = 'crm/clientcall_form.html'
    form_class = ClientCallModelForm

    def get_client_form(self):
        if not hasattr(self, 'client_form'):
            self.client_form = ClientModelForm(self.request.POST or None,
                                               initial={'phone': self.kwargs.get('phone', '')})
        return self.client_form

    def get_complaint_form(self):
        if not hasattr(self, 'complaint_form'):
            self.complaint_form = ComplaintModelForm(self.request.POST or None)
        return self.complaint_form

    def get_consultation_form(self):
        if not hasattr(self, 'consultation_form'):
            self.consultation_form = ConsultationModelForm(self.request.POST or None)
        return self.consultation_form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_form'] = self.get_client_form()
        context['complaint_form'] = self.get_complaint_form()
        context['consultation_form'] = self.get_consultation_form()
        # данные для использования в javascript
        context['handbook_data'] = dict()
        for category in Category.objects.prefetch_related('article_set'):
            context['handbook_data'][category.id] = [{'id': article.id, 'name': article.name} for article in
                                                     category.article_set.order_by('name')]
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        self.client_form = self.get_client_form()
        self.complaint_form = self.get_complaint_form()
        self.consultation_form = self.get_consultation_form()
        if form.is_valid() and self.client_form.is_valid():
            if form.cleaned_data['kind'] == ClientCall.KINDS.complaint and not self.complaint_form.is_valid():
                return self.form_invalid(form)
            if form.cleaned_data['kind'] == ClientCall.KINDS.consultation and \
                    not self.consultation_form.is_valid():
                return self.form_invalid(form)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        client = self.client_form.save(commit=False)
        client.user = self.request.user
        client.save()
        self.object = clientcall = form.save(commit=False)
        clientcall.client = client
        clientcall.user = self.request.user
        clientcall.save()
        messages.success(self.request, 'обращение зарегистрировано')
        if clientcall.kind == ClientCall.KINDS.complaint:
            complaint = self.complaint_form.save(commit=False)
            complaint.operator = self.request.user
            complaint.save()
            self.complaint_form.save_m2m()
            clientcall.complaint = complaint
            clientcall.save()
            messages.success(self.request, 'жалоба создана')
        elif clientcall.kind == ClientCall.KINDS.consultation:
            consultation = self.consultation_form.save()
            clientcall.consultation = consultation
            clientcall.save()
            messages.success(self.request, 'консультация сохранена')
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('index_page') #('surveys:survey', kwargs={'pk': 1}) + f'?call={self.object.pk}'


class ClientCallListView(LoginRequiredMixin, ListView):
    template_name = 'crm/clientcall_list.html'
    model = ClientCall
    paginate_by = 100
    queryset = ClientCall.objects.all().order_by('-id')
    # queryset = ClientCall.objects.select_related(
    #     'client', 'user', 'complaint', 'organization', 'region').prefetch_related(
    #     'complaint__topics').order_by('-created')


class ReportFormView(LoginRequiredMixin, FormView):
    template_name = 'crm/report_form.html'
    form_class = ReportForm
    success_url = reverse_lazy('crm:report_form')

    def form_valid(self, form):
        start = form.cleaned_data['start_date']
        end = form.cleaned_data['end_date']
        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet(f"отчёт по обращениям")
        headers = ["№ обращения",
                   "Дата и время поступления обращения",
                   "ФИО оператора / модератора",
                   "Регион",
                   "Наименование МО",
                   "ФИО заявителя",
                   "Конт.данные заявителя",
                   "Тематика обращения",
                   "Содержание обращения",
                   "Тип обращения",
                   "Статус обращения",
                   "Результат рассмотрения"]
        for i, header in enumerate(headers):
            ws.write(0, i, header, style=BOLD_CELL_CENTER)
        """
        for i, clientcall in enumerate(
                ClientCall.objects.filter(created__date__gte=start, created__date__lte=end).select_related(
                    'region', 'complaint', 'organization', 'client', 'user').prefetch_related(
                    'complaint__topics').order_by('created'), start=1):
            ws.write(i, 0, f'{clientcall.id}')
            ws.write(i, 1, timezone.localtime(clientcall.created).strftime('%d.%m.%Y %H:%M'))
            ws.write(i, 2, clientcall.user.get_full_name())
            ws.write(i, 3, str(clientcall.region) if clientcall.region else '')
            ws.write(i, 4, str(clientcall.organization) if clientcall.organization else '')
            ws.write(i, 5, clientcall.client.get_full_name() if clientcall.client else '')
            ws.write(i, 6, clientcall.client.phone if clientcall.client else '')
            topics = ', '.join(
                [str(topic) for topic in clientcall.complaint.topics.all()] if clientcall.complaint else '')
            ws.write(i, 7, topics)
            ws.write(i, 8, clientcall.text)
            ws.write(i, 9, clientcall.get_kind_display())
            ws.write(i, 10, clientcall.complaint.status if clientcall.complaint else '')
            ws.write(i, 11, clientcall.complaint.get_result_display() if clientcall.complaint else '')
        """
        for i, clientcall in enumerate(ClientCall.objects.filter(created__date__gte=start, created__date__lte=end), start=1):
            ws.write(i, 0, f'{clientcall.id}')
            ws.write(i, 1, timezone.localtime(clientcall.created).strftime('%d.%m.%Y %H:%M'))
            ws.write(i, 2, str(clientcall.fio_agent))
            ws.write(i, 3, str(clientcall.city) if clientcall.city else '')
            ws.write(i, 4, str(clientcall.pmsp) if clientcall.pmsp else '')
            ws.write(i, 5, clientcall.fio if clientcall.fio else '')
            ws.write(i, 6, clientcall.phone if clientcall.phone else '')
            topics = ', '.join(
                [str(topic) for topic in clientcall.complaint.topics.all()] if clientcall.complaint else '')
            ws.write(i, 7, topics)
            ws.write(i, 8, clientcall.reason)
            ws.write(i, 9, clientcall.kind)
            ws.write(i, 10, clientcall.result if clientcall.result else '')
            ws.write(i, 11, clientcall.result_more if clientcall.result_more else '')
        response = HttpResponse(
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        response['Content-Disposition'] = f'attachment; filename="CRM {start: %d.%m.%Y}-{end: %d.%m.%Y}.xls"'
        wb.save(response)
        return response


class ComplaintListView(LoginRequiredMixin, ListView):
    model = Complaint
    template_name = 'crm/complaints/complaint_list.html'
    queryset = Complaint.objects.order_by('-created').prefetch_related('topics').select_related(
        'clientcall', 'clientcall__region', 'clientcall__client', 'clientcall__organization',
        'operator', 'assignor', 'executor')


class ComplaintUpdateView(LoginRequiredMixin, UpdateView):
    model = Complaint
    template_name = 'crm/complaints/complaint_form.html'
    form_class = ComplaintUpdateModelForm

    def form_valid(self, form):
        complaint = form.save(commit=False)
        complaint.executor = complaint.assignor = self.request.user
        complaint.save()
        messages.success(self.request, 'жалоба обновлена')
        return redirect('crm:complaint_list')

tmc_new/apps/surveys/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import DetailView

from apps.crm.models import ClientCall
from apps.surveys.forms import AnswerModelForm
from apps.surveys.models import Survey, Interview


class SurveyView(LoginRequiredMixin, DetailView):
    model = Survey
    template_name = 'surveys/survey.html'

    def post(self, *args, **kwargs):
        self.object = survey = self.get_object()
        answer_forms = self.get_answer_forms()
        if all([form.is_valid() for form in answer_forms]):
            client_call_pk = self.request.GET.get('call')
            client_call = ClientCall.objects.filter(pk=client_call_pk).first()
            client = client_call.client if client_call else None
            interview = Interview.objects.create(survey=survey, operator=self.request.user, client=client)
            for form in answer_forms:
                answer = form.save(commit=False)
                answer.interview = interview
                answer.save()
            messages.success(self.request, 'анкета сохранена')
            return redirect('index_page')
        else:
            return self.render_to_response(self.get_context_data(**kwargs))

    def get_answer_forms(self):
        if not hasattr(self, 'answer_forms'):
            self.answer_forms = list()
            for question in self.object.questions.all().order_by('text'):
                self.answer_forms.append(AnswerModelForm(self.request.POST or None,
                                                         prefix=question.id, initial={'question': question}))
        return self.answer_forms

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answer_forms'] = self.get_answer_forms()
        return context

tmc_new/apps/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.base import TemplateResponseMixin
from django.views.generic.edit import BaseUpdateView

from apps.users.forms import UserModelForm


class CabinetIndexView(LoginRequiredMixin, TemplateView):
    template_name = 'users/cabinet/index.html'


class CabinetUpdateUserInfo(LoginRequiredMixin, TemplateResponseMixin, BaseUpdateView):
    template_name = 'users/cabinet/update_user_info.html'
    form_class = UserModelForm
    success_url = reverse_lazy('users:cabinet:index')

    def get_object(self, queryset=None):
        return self.request.user

tmc_new/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script type="text/javascript" src="https://demov5_kz.hostedcc.ru/agentdesktop/app/lib/servicepattern-sdk-v1.js"></script>
    <script type="text/javascript" src="https://demov5_kz.hostedcc.ru/libs/servicepatternapi-dev.js"></script>
    <!-- <script type="text/javascript" src="https://demov5_kz.hostedcc.ru/agentdesktop/AgentDesktopSdkTest.jsp"></script> -->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://tmc1312.kz/libs/servicepattern-sdk-v1.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/css.css' %}">
    {% block staticfiles %}
    {% endblock staticfiles %}
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <title>Form</title>
</head>
<body>
    <div id="header" class="row main_container p-1" >
        <div class="col-10">
            {% block title %}  {% endblock %}
        </div>
        <div class="col-2 row">
        {% if not request.user.is_authenticated %}
                <button style="color: white; width: 80%;" class="btn col p-1" type="button">Войти</button>
        {% else %}
                <div class="col">
                    <button class="btn" id="requestUserLink" type="button">{{ request.user.username }}</button>
                </div>
                <div class="col">
                    <button onclick="logout()"  id="logoutLink" class="btn" type="button">Выйти</button>
                </div>
        {% endif %}
        </div>
    </div>
    <div style="overflow-x: hidden;" class="main_container">
    {% block content %}
    {% endblock %}
    
    </div>
</body>
<script>
     function logout() {    
        link = "{% url 'logout' %}"
        return window.location = link
    }   
</script>

<style>
    h3{
        font-size: 13px;
        font-weight: bold;
    }
    div{
        box-sizing: border-box;
    }
    .main_container{
        box-sizing: border-box;
        width: 99%;
        margin: 0 auto;
        overflow: hidden;
    }
</style>

</html>

tmc_new/templates/index.html
{% extends 'base.html' %}
{% block html_title %}{{ site.name }} | Главная{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active" aria-current="page">Главная</li>
{% endblock breadcrumb %}


{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-4 mt-3">
        <ul class="list-group">
          <a href="{% url 'crm:new_clientcall_form' %}" class="list-group-item list-group-item-action">
            <i class="fas fa-phone mr-2"></i>Новое обращение</a>
          <a href="{% url 'crm:clientcall_list' %}" class="list-group-item list-group-item-action">
            <i class="fas fa-list mr-2"></i>Все обращения</a>
          <a href="{% url 'crm:complaint_list' %}" class="list-group-item list-group-item-action">
            <i class="fas fa-exclamation-triangle mr-2"></i>Жалобы</a>
          <a href="{% url 'crm:report_form' %}" class="list-group-item list-group-item-action">
            <i class="fas fa-table mr-2"></i>Отчёты</a>
        </ul>
      </div>
      <div class="col-md-8 mt-3">
        <h3>Статистика</h3>
        <table class="table table-lg">
          <tr>
            <td>Всего обращений</td>
            <td class="text-success">{{ clientcall_count_all }}</td>
          </tr>
          <tr>
            <td>Обращений за текущий месяц</td>
            <td class="text-success">{{ clientcall_count_month }}</td>
          </tr>
          <tr>
            <td>Всего жалоб</td>
            <td class="text-danger">{{ complaint_count_all }}</td>
          </tr>
          <tr>
            <td>Жалоб за текущий месяц</td>
            <td class="text-danger">{{ complaint_count_month }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

tmc_new/templates/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/css.css' %}">
    <title>Form</title>
</head>
<body>
    {% if message %}
    <div class="mx-auto mt-3 p-3" style="width: 35%; background-color: rgb(173, 40, 40);">
        <h3 class="my-auto text-center; width: 100%;" style="color: white; font-size: 18px; font-weight: bold;">{{ message }}</h3>
    </div>
    {% endif %}
<div class="text-center pl-5 pr-5 pb-3" style="border-radius: 8px; width: 20%; position: absolute; top: 32%; left: 37%; border: 2px solid #000; box-shadow: rgb(189, 189, 189) 4px 4px 4px 4px;">
    <h3 class="p-2" style="border-radius: 4px 4px 0px 0px; background-color: #000; color: white; font-weight: bold;">Авторизация</h3>
    <form method="POST">
        {% csrf_token %}
        <div class="pt-3 pb-3 mt-5 d-flex justify-content-center">
            <label style="font-size: 16px; font-weight: bold; min-width: 28px;" for="username">Логин</label>
            <input style="padding-left: 3px; padding-right: 8px; width: 55%; border: none; border-bottom: 2px solid gray; outline: none;" type="text" id="username" name="username">
        </div>
        <div class="d-flex justify-content-center pt-3 pb-3 mb-4">
            <label style="font-size: 16px; font-weight: bold; min-width: 28px;" for="password">Пароль</label>
            <input style="padding-left: 3px; padding-right: 8px; width: 55%; border: none; border-bottom: 2px solid gray; outline: none;" type="password" id="password" name="password">
        </div>
        <button class="btn btn-dark" type="submit">Отправить</button>
    </form>
</div>
</body>
</html>